### ISSUE TITLE
Find a nice way to handle errors

### ISSUE THREAD

**Issue by grsabreu** [Astrocoders/reform#1]

**Comment by StevenLangbroek** [comment]
Hey! Just saw you post the link to this in the Reason discord. As I'm still in the process of exploring, I'm not sure how much I can contribute yet, but I'd suggest taking a look at the state that redux-form keeps track of:

- [Field-level](https://redux-form.com/7.1.2/docs/api/field.md/#meta-props)
- [Form-level(these are a bit scattered with methods in it as well](https://redux-form.com/7.1.2/docs/api/props.md/#-code-props-code-)

There are a lot of libraries that deal with validation, I've always liked [validatejs](http://validatejs.org/) but I'm sure there are better ways of composing multiple validators to a schema-validator in ReasonML that I'm not aware of yet.

If you want to bounce some ideas off someone let me know, I'm on the Discord (Steven#4796).

**Comment by grsabreu** [comment]
Awesome, thanks for the tips!
I'm really putting a thinking on this now, for now, I think I'm just going to let the users handle the messages manually and enhance when I know more about OCaml itself

**Comment by grsabreu** [comment]
I used redux-form in other projects before and it is really awesome, the thing is that now there is no context API equivalent, I would need to do some JS binding to make this work, but does not feel quite right.
Anyways, gonna keep this issue opened and put more findings here

**Comment by grsabreu** [comment]
Nice ideas on https://gist.github.com/WolfDan/5d4e7f3c7d994b1b0a3bb4e4c6f07d66
cc @WolfDan

**Comment by grsabreu** [comment]
For now there is only a global error https://github.com/Astrocoders/reform/blob/master/re/ReForm.re#L41
Gonna try to implement a PR with @WolfDan ideas as soon as I can

**Comment by grsabreu** [comment]
We'll need fieldslib here https://github.com/janestreet/fieldslib/
https://github.com/janestreet/base/blob/master/README.org

**Comment by grsabreu** [comment]
Alright, I think this gets it done for now https://github.com/Astrocoders/reform/pull/8/files
I just need to rename some stuff

**Comment by grsabreu** [comment]
I think this will do it for now https://github.com/Astrocoders/reform/commit/c18f04ec2221b0db346f480dbd9914e1c2516ed8
