### ISSUE TITLE
Docs: TODO List Demo

### ISSUE THREAD

**Issue by anabastos** [Astrocoders/reform#138]
I think that a TODO list is a great example of the tool to show on the `Try Out` docs session.

**Comment by fakenickels** [comment]
Agreed!

**Comment by arthurbarroso** [comment]
Created a TODO list application for this issue. Please check it [here](https://github.com/arthurbarroso/reform.re-todolist). Still misses css and stuff but works and should fit the documentation's needs.

**Comment by cironunes** [comment]
I think this can be closed now? :)

**Comment by fakenickels** [comment]
Well remembered! I totally forgot
