### ISSUE TITLE
Move formState type outside of Make

### ISSUE THREAD

**Issue by selenir** [Astrocoders/reform#144]
Currently `formState` variant is defined inside of `Make` functor, however it doesn't depend on `Config` type.
It would be nice if we could move formState outside of it so it could be referenced directly as `ReForm.Dirty`, etc.

```
/* MyForm.re */

module Form = ReForm.Make(...);
/* only want to export use */
let use = Form.use;

/* App.re */
let form = MyForm.use(...);
let hasErrors = form.state.formState == ReForm.Errored; /* not MyForm.Form.Errored */
```

**Comment by fakenickels** [comment]
That's a good idea! If you can send a PR I can ship it right away.
It's actually on our plans to try to move the most we can to outside the functor

**Comment by selenir** [comment]
I will get on it when I get back home. Also I think this could be breaking change. Should we leave keep reference to formState in functor as well for backward compatibility?

**Comment by fakenickels** [comment]
Looks good to me!
