### ISSUE TITLE
Feature : top level error

### ISSUE THREAD

**Issue by DCKT** [Astrocoders/reform#146]
Hello,

It looks like we cannot raise a top level error (unbound to a field). This could be useful for special behavior like API call in the `onSubmit`.

What do you think about this ?

**Comment by fakenickels** [comment]
We had a toplevel (global error) for the form state in the past, to be honest I can't recall why we decided to not include in the current version. But I like the idea of bringing it back

Probably we could extend the `Errored` type to include a `option(string)`
https://github.com/Astrocoders/reform/blob/master/packages/bs-reform/src/ReForm.re#L21

**Comment by DCKT** [comment]
The `SubmitError` should be enough for most cases 👍

**Comment by DCKT** [comment]
Is it possible to create a new version release with this feature ? I really need it (and I don't know how to use git as npm registery with lerna 😅)

**Comment by fakenickels** [comment]
Hey sorry about the delay! Will be pushing today still in a couple of hours 🙏
