### ISSUE TITLE
Should I use option for state lense ?

### ISSUE THREAD

**Issue by DCKT** [Astrocoders/reform#147]
Hello,

I'm using a lot of `option(something)` but I found I can't set any values to `None`, it does nothing.
I'm not sure but I think it's because `value` of html input are either `string`, `int`, `float`, `bool` but not really `undefined` ? 

My use case here is `option(int)`, I don't want to set an initial value to my field, I want it blank and keep the type as an `int`.

How do you manage this kind of case ? 🤔 

Thanks for your help !

**Comment by DCKT** [comment]
I tried to create a custom type but it was a lot of overhead so I end up using a `string` 😃

**Comment by fakenickels** [comment]
A option(string) sounds good for me!
