### ISSUE TITLE
bs-reform v9.7.0 "raiseSubmitFailed" missing declaration 

### ISSUE THREAD

**Issue by Ben-Davis1** [Astrocoders/reform#153]
Hey.

Should be a quick fix but I noticed that the declaration for the `raiseSubmitFailed` variable in `ReForm.re` is missing as of v9.7.0. 

Looking at previous versions, I believe the variable should be defined with the following but I could be wrong:

`let raiseSubmitFailed = error => send(RaiseSubmitFailed(error));`

Cheers

**Comment by fakenickels** [comment]
Thanks! a
