### ISSUE TITLE
Field doesn't rerender on render prop change

### ISSUE THREAD

**Issue by a-gierczak** [Astrocoders/reform#155]
Because of [this useMemo](https://github.com/Astrocoders/reform/blob/master/packages/bs-reform/src/ReForm.re#L153) Field component won't get rerendered when renderProp changes.
I know this is for optimization purposes, but I think we should be able to opt-out from it.

Consider this scenario:
```
let make = () => {
  let (isDisabled, setIsDisabled) = React.useState(_ => false);

  /* some external event  */
  React.useEffect1(() => {
    setIsDisabled(_ => false);
  }, ...);


  <Field field render={({value, handleChange}) => {
    <input value onChange=handleChange disabled=isDisabled />
  }}
};
```

When isDisabled changes input won't be enabled, because of stale closure.

**Comment by fakenickels** [comment]
Thanks for reporting.

When I need to do a special rendering for a input I always end up removing it out of the Field component.
But if it'll help ergonomics maybe we can have a `dependencies` optional param for the Field component.

```reason
<Field dependencies=[|isDisabled|] />
```

I don't wanted to extend too much the functionality of Field, but we can analyse the situation

**Comment by selenir** [comment]
I think better approach would be to not memoize by default, because bugs like that could be confusing for new users and in most cases, additional renders don't cause that much performance overhead. Also using Field may be the default approach by new users, providing that it's documented in "basic usage" on this repo :)

Same functionality could be achieved by using useCallback on the render prop.

**Comment by ktrzos** [comment]
Hello! Have similar issue. Initially I start with disabled `<select>` field with no options, and after clicking a separate button (which loads data), the `options` and `disabled` attributes changes, but the component inside of `render` prop is not rerendered. Can something be done with this?

**Comment by ktrzos** [comment]
@fakenickels 

Any info if this issue is resolved? The PR is still "Open" :).

**Comment by fakenickels** [comment]
I'm doing a clean up getting ready for the upgrade and we'll keep up with this issue soon 😉
