### ISSUE TITLE
Form State different type

### ISSUE THREAD

**Issue by ri7nz** [Astrocoders/reform#156]
Hello, I'm use `Reform`. 

I have some problem with `type` in my form. 

I defined state of form like this: 
```reason
module StateLenses = [%lenses
  type state = {
    userId: int,
    title: string,
    body: string,
  }
];
```
But, when I want request to `API`, the payload of `request` it's different.   
![image](https://user-images.githubusercontent.com/16365952/76146924-09112400-60ca-11ea-9525-4bc4d20248e7.png)

I'm new corner, i didn't know how to solve this :smile: .
Okay, this is an example project with my problem :smile: 
https://github.com/ri7nz/reform-reproduce

thank you

**Comment by fakenickels** [comment]
Hey there, the request looks about right with the `type state`. Could you explain what part of the `request` payload is wrong? The type of userId?

**Comment by ri7nz** [comment]
@fakenickels yes, the type of `userId` it's wrong. 

```
(first, render the form) --> userId is 0 --> user change and put 2 --> userId is "2"
```

I'm expect `userId` it's `int` before request to the API.

**Comment by fakenickels** [comment]
I see, the ReForm usage and types are correct to me!
Probably it is getting turned into string from the encode you are using https://github.com/ri7nz/reform-reproduce/blob/master/src/Form.re#L126. Have you tried debugging the encode function?

**Comment by ri7nz** [comment]
@fakenickels But, maybe you can check at this line https://github.com/ri7nz/reform-reproduce/blob/master/src/Form.re#L95 

for the encode, I will be check again & give it feedback, soon.

**Comment by DCKT** [comment]
@ri7nz It's not a reform problem it's the default behavior in every browser check this 
https://stackoverflow.com/questions/35791767/html-input-type-number-still-returning-a-string-when-accessed-from-javascript

**Comment by ri7nz** [comment]
Hello @fakenickels & @DCKT , thank you so much for response my issue. I'm close this is issue :+1:

**Comment by fakenickels** [comment]
@ri7nz any questions feel free to reach me in Discord!
