### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by vmarcosp** [Astrocoders/reform#158]
Hey @fakenickels as we talked before, I have a logo proposal for Reform:
![v1](https://user-images.githubusercontent.com/20327229/78918878-79171f00-7a67-11ea-8f0f-121a75c633dd.png)

You can download the files using this [link](https://www.figma.com/file/WYL0s7wMpuinD0is2d5k8l/Reform-Logo?node-id=0%3A1)

**Comment by fakenickels** [comment]
Amazing!!! Thanks a lot @vmarcosp. I loved it
