### ISSUE TITLE
Warning `'with' clause is useless` whenever state lenses have only one field

### ISSUE THREAD

**Issue by nireno** [Astrocoders/reform#195]
Is there any way to avoid the following warning when using the [%lenses ...] ppx when the state has only one field?

```
File "_none_", line 1:
Warning 23: all the fields are explicitly listed in this record:
the 'with' clause is useless.
```

Sample code that generates the above error:

```
module StateLenses = [%lenses
  type state = {
    email: string,
  }
];
```

I've been adding a dummy field in there just to silence the warning.

**Comment by fakenickels** [comment]
I added a check in the past to prevent that in lenses-ppx 

https://github.com/Astrocoders/lenses-ppx/blob/master/packages/ppx/src/LensesPpx.re#L20-L22

Which version of lenses-ppx are you using?

**Comment by nireno** [comment]
@fakenickels I was working off of the demo project in this repo which was on version 5. I created a pull request that updates the package. 

Thank you.

**Comment by fakenickels** [comment]
That's fantastic, thank you @nireno
