### ISSUE TITLE
Submitting state

### ISSUE THREAD

**Issue by thangngoc89** [Astrocoders/reform#30]
`onSubmit` callback has a method named `setSubmitting` but the children function doesn't expose that state. I can send a PR to expose this. What do you think?

**Comment by grsabreu** [comment]
The state is exposed in form.isSubmitting

**Comment by grsabreu** [comment]
```
  type state = {
    values,
    isSubmitting: bool,
    errors: list((Config.fields, option(string))),
    error: option(string)
  };
  /* Type of what is given to the children */
  type reform = {
    form: state,
    handleChange: (Config.fields, value) => unit,
    handleGlobalValidation: option(string) => unit,
    handleSubmit: unit => unit,
    getErrorForField: Config.fields => option(string)
  };
```

currently, this is are the exposed utils
the `state` is the `form` field of the record passed

**Comment by thangngoc89** [comment]
Thank you. I need to take (another) closer look at the source. 👍

**Comment by grsabreu** [comment]
it is also pointed out here! https://github.com/Astrocoders/reform#form-paramsstate
maybe we should update the demos to make this clearer
