### ISSUE TITLE
Validator API: option(string) => Js.Result.t(unit, string)

### ISSUE THREAD

**Issue by thangngoc89** [Astrocoders/reform#34]
Currently, validator API looks like this: 

```reason
Custom(state => option(string))
```

Which is IMHO pretty confusing and requires you to read doc/source code to actually know what is `option(string)` actually means.

I would suggest that we use result type. It's in OCaml 4.0.3 but Bucklescript provides us a compat type [Js.Result.t](https://bucklescript.github.io/bucklescript/api/Js.Result.html)

Usage: 

```reason
open Js.Result;
type validateResult = Js.Result.t(unit, string);
...
Custom(values => values.password == "123" ? Error("Really") : Ok())
```

And I think using result type should be self-described

**Comment by grsabreu** [comment]
Sounds interesting

**Comment by grsabreu** [comment]
But for me it looks similar, using option or Result in this case.
Let's see what the others think about this

**Comment by fakenickels** [comment]
We have now something similar to this
Valid | Error(string)
