### ISSUE TITLE
`resetFormState` handler

### ISSUE THREAD

**Issue by fakenickels** [Astrocoders/reform#41]
Will be passed to the children and to the `onSubmit` handler, so the consumer can programatically reset the form state

**Comment by amythos** [comment]
hello @grsabreu , i only see the `resetFormState` handler in `onSubmit` handler, but not in the children. so i can't reset the form state when i click the cancel button in my form.

**Comment by grsabreu** [comment]
thanks for the suggestion @amythos , totally makes sense indeed to pass it for the children. Gonna ship this soon.

**Comment by fakenickels** [comment]
closed by #81
