### ISSUE TITLE
Support checkbox/radio button

### ISSUE THREAD

**Issue by jack-lewin** [Astrocoders/reform#52]
The `handleDomFormChange` method doesn't currently account for the checkbox or radio input types:

https://github.com/Astrocoders/reform/blob/4553bd8b21e3d82ba772e6def066dc98578a36f5/re/ReForm_Helpers.re#L1-L4

I tried fixing this by adding a switch:

```reason
let handleDomFormChange = (handleChange, event) => {
  let domEl = ReactDOMRe.domElementToObj(ReactEventRe.Form.target(event));

  switch (domEl##type_) {
  | "checkbox" => handleChange(domEl##checked);
  | "radio" => handleChange(domEl##checked);
  | _ => handleChange(domEl##value);
  };
};
```

But this doesn't work as Reform currently only supports strings, so it's not as easy as I first thought. Any thoughts on how to fix this?

**Comment by grsabreu** [comment]
I think we'll include a helper to handle better boolean values while implementing this https://github.com/Astrocoders/reform/issues/23

**Comment by jack-lewin** [comment]
Awesome 🙂 Let me know if I can help in any way

**Comment by grsabreu** [comment]
Closing in favor of #23
