### ISSUE TITLE
Broken link in repo description

### ISSUE THREAD

**Issue by mikaello** [Astrocoders/reform#68]
The link to https://astrocoders.com/reform that is in the repo description is broken

![broken](https://user-images.githubusercontent.com/2505178/53186990-64c55800-3602-11e9-945d-542edcc75cae.png)

It seems like you have moved all your open source projects to one page: https://astrocoders.com/open-source

**Comment by guilhermedecampo** [comment]
Thank you for the issue!

**Comment by grsabreu** [comment]
Netlify redirects

**Comment by fakenickels** [comment]
Fixed, site is at https://astrocoders.dev/reform
