### ISSUE TITLE
Use README as docs, include help sections for Hooks params and Validations list with demos

### ISSUE THREAD

**Issue by fakenickels** [Astrocoders/reform#96]
README docs ftw

tired:

an explanation for each hook param
an explanation for each Validator

wired:
think how to make this automatic

**Comment by guilhermedecampo** [comment]
we can use something related or build our own https://github.com/SimplrJS/ts-docs-gen for reason.

**Comment by fakenickels** [comment]
There is odoc, not sure if it's playing well with Reason

**Comment by fakenickels** [comment]
kinda conflicts with #67 , we should keep both. A more extensive and detailed one in docusaurus but keep some quick snippets in the README

**Comment by arthurbarroso** [comment]
I'd like to help with docusaurus. Sent @fakenickels a private message on twitter.
